# $Id$
#
# @TEST-EXEC:  hilti-build %INPUT -o a.out 
# @TEST-EXEC:  ./a.out >output 2>&1
# @TEST-EXEC:  test-diff output
# 
# These are all supposed to throw exceptions.

module Main

import Hilti

void run() {
    local int32 i
    local int64 s
    local ref<list<int32>> l
    local iterator<list<int32>> c
    
    l = new list<int32>
    list.push_back l 1

    c = first l
    c = incr c
    list.erase c
    
}     

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int32 i
    local int64 s
    local ref<list<int32>> l
    local iterator<list<int32>> c
    
    l = new list<int32>
    list.push_back l 1

    c = first l
    list.erase c
    list.erase c
    
}     

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int32 i
    local int64 s
    local ref<list<int32>> l
    local iterator<list<int32>> c
    
    l = new list<int32>
    list.push_back l 1

    c = first l
    list.erase c
    c = first l
    list.erase c
    
}     

### @TEST-START-NEXT

module Main

import Hilti

void run() {
    local int32 i
    local int64 s
    local ref<list<int32>> l
    local iterator<list<int32>> c
    
    l = new list<int32>
    list.push_back l 1

    c = first l
    list.erase c
    c = incr c
    
}     



