>>> x = call foo ()
wrong-calls.hlt:8: error, called function does not return a value


1 error found
